version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: odoodb
    restart: unless-stopped
    ports:
      - "4466:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpassword
      POSTGRES_DB: odoodb
    volumes:
      - odoodb-data:/var/lib/postgresql/data

volumes:
  odoodb-data:
